INSERT INTO `giftmefive`.`article` (`name`, `market_link`, `picture`, `description`, `price`, `is_gifted`, `list_id`) VALUES ('Micro-onde', 'https://www.amazon.fr/Micro-Ondes-MW2-MM20PF-BK-D%C3%A9cong%C3%A9lation-Puissance/dp/B08CCDDCCC/ref=sr_1_5?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=38MQ97N7N7ON4&dchild=1', 'https://m.media-amazon.com/images/I/81nB2TamwpL._AC_SL1500_.jpg', 'Je veux ce micro-onde','99.99', '0', '3');
INSERT INTO `giftmefive`.`article` (`name`, `market_link`, `picture`, `description`, `price`, `is_gifted`, `list_id`) VALUES ('Brosse à dent ', 'https://www.amazon.fr/Oral-B-Électrique-Rechargeable-Pression-Brossette/dp/B094W9KT4Y/ref=sr_1_5?dchild=1', 'https://m.media-amazon.com/images/I/7110q+qB1JS._AC_SL1500_.jpg', 'Je veux la brosse à dent Oral-B PRO 600','21.40', '0', '3');
INSERT INTO `giftmefive`.`article` (`name`, `market_link`, `picture`, `description`, `price`, `is_gifted`, `list_id`) VALUES ('Manette PS5', 'https://www.amazon.fr/PlayStation-officielle-DualSense-rechargeable-Compatible/dp/B08H99BPJN/ref=sr_1_5?dchild=1', 'https://m.media-amazon.com/images/I/71lPDuOqgKL._AC_SL1500_.jpg', 'Je veux la manette PS5 blanche','69.90', '0', '3');
INSERT INTO `giftmefive`.`article` (`name`, `market_link`, `picture`, `description`, `price`, `is_gifted`, `list_id`) VALUES ('Mixeur', 'https://www.amazon.fr/s?k=magimix+cook+expert+connect&sprefix=magimix+cook+expert+conne%2Caps%2C89&ref=nb_sb_ss_ts-doa-p_1_25', 'https://m.media-amazon.com/images/I/512cNTldn5L._AC_SL1000_.jpg', 'Je veux le magimix expert connect','1499.00', '1', '3');
INSERT INTO `giftmefive`.`article` (`name`, `market_link`, `picture`, `description`, `price`, `is_gifted`, `list_id`) VALUES ('Ordinateur', 'https://www.amazon.fr/Dell-Inspiron-Ordinateur-Processeur-Graphiques/dp/B08XZQLFRF/ref=sr_1_5?__mk_fr_FR=ÅMÅŽÕÑ&crid=XNEVBWDGJQ9W&dchild=1', 'https://images-na.ssl-images-amazon.com/images/G/08/apparel/rcxgs/tile._CB483369919_.gif', 'Je veux le Dell Inspirion', '499', '0', '3');
INSERT INTO `giftmefive`.`article` (`name`, `market_link`, `picture`, `description`, `price`, `is_gifted`, `list_id`) VALUES ('Frigo', 'https://www.amazon.fr/Réfrigérateur-américain-GSX961MCVZ-Door-Door/dp/B07YY5NT2T/ref=sr_1_12?dchild=1', 'https://m.media-amazon.com/images/I/31YyOzNThrL._AC_.jpg', 'Je veux le LG Side By Side GSX961MCVZ', '2351', '1', '3');
INSERT INTO `giftmefive`.`article` (`name`, `market_link`, `picture`, `description`, `price`, `is_gifted`, `list_id`) VALUES ('Fauteuil', 'https://www.amazon.fr/IDMarket-Fauteuil-scandinave-Tissu-Anthracite/dp/B07QX8ZKBF/ref=sr_1_5?dchild=1', 'https://m.media-amazon.com/images/I/41U2ZuNxJzL._AC_SX425_.jpg', 'Je veux le IDMarket', '154.9', '0', '3');
INSERT INTO `giftmefive`.`article` (`name`, `market_link`, `picture`, `description`, `price`, `is_gifted`, `list_id`) VALUES ('Battlefield 2042', 'https://www.amazon.fr/Electronic-Arts-198874-Battlefield-PlayStation/dp/B096KG6M2K/ref=sr_1_1?dchild=1', 'https://m.media-amazon.com/images/I/81jKBuMVq+S._AC_SL1500_.jpg', 'Je veux battlefield 2042', '67.99', '0', '3');


